import { resolve } from 'node:path'
import { defineConfig } from 'vite'

// 多页面站点：首页 + 每道题一个独立页面。加题时在 input 里加一行即可。
export default defineConfig({
  root: '.',
  base: '/leetcode-tutorials/',
  build: {
    rollupOptions: {
      input: {
        home: resolve(__dirname, 'index.html'),
        p1: resolve(__dirname, "src/problems/1-two-sum/index.html"),
        p3: resolve(__dirname, "src/problems/3-longest-substring-without-repeating-characters/index.html"),
        p5: resolve(__dirname, "src/problems/5-longest-palindromic-substring/index.html"),
        p11: resolve(__dirname, "src/problems/11-container-with-most-water/index.html"),
        p15: resolve(__dirname, "src/problems/15-3sum/index.html"),
        p19: resolve(__dirname, "src/problems/19-remove-nth-node-from-end-of-list/index.html"),
        p20: resolve(__dirname, "src/problems/20-valid-parentheses/index.html"),
        p21: resolve(__dirname, "src/problems/21-merge-two-sorted-lists/index.html"),
        p23: resolve(__dirname, "src/problems/23-merge-k-sorted-lists/index.html"),
        p33: resolve(__dirname, "src/problems/33-search-in-rotated-sorted-array/index.html"),
        p39: resolve(__dirname, "src/problems/39-combination-sum/index.html"),
        p48: resolve(__dirname, "src/problems/48-rotate-image/index.html"),
        p49: resolve(__dirname, "src/problems/49-group-anagrams/index.html"),
        p53: resolve(__dirname, "src/problems/53-maximum-subarray/index.html"),
        p54: resolve(__dirname, "src/problems/54-spiral-matrix/index.html"),
        p55: resolve(__dirname, "src/problems/55-jump-game/index.html"),
        p56: resolve(__dirname, "src/problems/56-merge-intervals/index.html"),
        p57: resolve(__dirname, "src/problems/57-insert-interval/index.html"),
        p62: resolve(__dirname, "src/problems/62-unique-paths/index.html"),
        p70: resolve(__dirname, "src/problems/70-climbing-stairs/index.html"),
        p73: resolve(__dirname, "src/problems/73-set-matrix-zeroes/index.html"),
        p76: resolve(__dirname, "src/problems/76-minimum-window-substring/index.html"),
        p79: resolve(__dirname, "src/problems/79-word-search/index.html"),
        p91: resolve(__dirname, "src/problems/91-decode-ways/index.html"),
        p98: resolve(__dirname, "src/problems/98-validate-binary-search-tree/index.html"),
        p100: resolve(__dirname, "src/problems/100-same-tree/index.html"),
        p102: resolve(__dirname, "src/problems/102-binary-tree-level-order-traversal/index.html"),
        p104: resolve(__dirname, "src/problems/104-maximum-depth-of-binary-tree/index.html"),
        p105: resolve(__dirname, "src/problems/105-construct-binary-tree-from-preorder-and-inorder-traversal/index.html"),
        p121: resolve(__dirname, "src/problems/121-best-time-to-buy-and-sell-stock/index.html"),
        p124: resolve(__dirname, "src/problems/124-binary-tree-maximum-path-sum/index.html"),
        p125: resolve(__dirname, "src/problems/125-valid-palindrome/index.html"),
        p128: resolve(__dirname, "src/problems/128-longest-consecutive-sequence/index.html"),
        p133: resolve(__dirname, "src/problems/133-clone-graph/index.html"),
        p139: resolve(__dirname, "src/problems/139-word-break/index.html"),
        p141: resolve(__dirname, "src/problems/141-linked-list-cycle/index.html"),
        p143: resolve(__dirname, "src/problems/143-reorder-list/index.html"),
        p152: resolve(__dirname, "src/problems/152-maximum-product-subarray/index.html"),
        p153: resolve(__dirname, "src/problems/153-find-minimum-in-rotated-sorted-array/index.html"),
        p190: resolve(__dirname, "src/problems/190-reverse-bits/index.html"),
        p191: resolve(__dirname, "src/problems/191-number-of-1-bits/index.html"),
        p198: resolve(__dirname, "src/problems/198-house-robber/index.html"),
        p200: resolve(__dirname, "src/problems/200-number-of-islands/index.html"),
        p206: resolve(__dirname, "src/problems/206-reverse-linked-list/index.html"),
        p207: resolve(__dirname, "src/problems/207-course-schedule/index.html"),
        p208: resolve(__dirname, "src/problems/208-implement-trie-prefix-tree/index.html"),
        p211: resolve(__dirname, "src/problems/211-design-add-and-search-words-data-structure/index.html"),
        p212: resolve(__dirname, "src/problems/212-word-search-ii/index.html"),
        p213: resolve(__dirname, "src/problems/213-house-robber-ii/index.html"),
        p217: resolve(__dirname, "src/problems/217-contains-duplicate/index.html"),
        p226: resolve(__dirname, "src/problems/226-invert-binary-tree/index.html"),
        p230: resolve(__dirname, "src/problems/230-kth-smallest-element-in-a-bst/index.html"),
        p235: resolve(__dirname, "src/problems/235-lowest-common-ancestor-of-a-binary-search-tree/index.html"),
        p238: resolve(__dirname, "src/problems/238-product-of-array-except-self/index.html"),
        p242: resolve(__dirname, "src/problems/242-valid-anagram/index.html"),
        p252: resolve(__dirname, "src/problems/252-meeting-rooms/index.html"),
        p253: resolve(__dirname, "src/problems/253-meeting-rooms-ii/index.html"),
        p261: resolve(__dirname, "src/problems/261-graph-valid-tree/index.html"),
        p268: resolve(__dirname, "src/problems/268-missing-number/index.html"),
        p269: resolve(__dirname, "src/problems/269-alien-dictionary/index.html"),
        p271: resolve(__dirname, "src/problems/271-encode-and-decode-strings/index.html"),
        p295: resolve(__dirname, "src/problems/295-find-median-from-data-stream/index.html"),
        p297: resolve(__dirname, "src/problems/297-serialize-and-deserialize-binary-tree/index.html"),
        p300: resolve(__dirname, "src/problems/300-longest-increasing-subsequence/index.html"),
        p322: resolve(__dirname, "src/problems/322-coin-change/index.html"),
        p323: resolve(__dirname, "src/problems/323-number-of-connected-components-in-an-undirected-graph/index.html"),
        p338: resolve(__dirname, "src/problems/338-counting-bits/index.html"),
        p347: resolve(__dirname, "src/problems/347-top-k-frequent-elements/index.html"),
        p371: resolve(__dirname, "src/problems/371-sum-of-two-integers/index.html"),
        p417: resolve(__dirname, "src/problems/417-pacific-atlantic-water-flow/index.html"),
        p424: resolve(__dirname, "src/problems/424-longest-repeating-character-replacement/index.html"),
        p435: resolve(__dirname, "src/problems/435-non-overlapping-intervals/index.html"),
        p572: resolve(__dirname, "src/problems/572-subtree-of-another-tree/index.html"),
        p647: resolve(__dirname, "src/problems/647-palindromic-substrings/index.html"),
        p1143: resolve(__dirname, "src/problems/1143-lcs/index.html"),
      },
    },
  },
})
